import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./styles/globals.css";

const mainFontFamily = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Step to Go",
  description: "Generated by create next app",
  icons:{
    icon: ['/icon.ico']
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mainFontFamily.className}>{children}</body>
    </html>
  );
}
